### ISSUE TITLE
Questions and requests!

### ISSUE THREAD

**Issue by zelk696** [krogenth/G2Data#1]
1,このデータは、最新のものですか？
2,私たちは、日本語版の"グランディア2(HD)"でも使用できますか？

1. Is this data up to date?
2, Can we use the Japanese version of "Grandia 2 (HD)"?

**Comment by krogenth** [comment]
翻訳が不十分な場合は申し訳ありません

1、G2Dataは非推奨であり、いくつかのパーツが欠落しているか、一部のパーツを読み違えています。可能であれば[G2DataGUI](https://github.com/krogenth/G2DataGUI)を使用することをお勧めします

2、G2DataはAnniversary Editionの間に作成されたため、Anniversary Editionの古いファイルレイアウトがまだ必要です（これは、必要に応じてファイルを移動することで解決できます）。 それが現在読み書きするファイルは、私の知る限り、プラットフォーム間で同じです。

互換性を確認したい場合は、content / data / afs / xls_data / MS_PARAM.BINのバージョンを送信できます

**Comment by zelk696** [comment]
教えてくれてありがとう
この新しいデータファイルを利用したいと思います。
Thank you for teaching me.
I would like to utilize this newer data file!

**Comment by krogenth** [comment]
問題ない。 問題が発生した場合は、G2DataGUIリポジトリに問題を作成してください。
